-- =========================================================================
-- Supabase Setup Script for NewsImpact
-- Run this script in the Supabase SQL Editor to create the required tables.
-- =========================================================================

-- 1. Create the 'news' table
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT,
    url TEXT UNIQUE NOT NULL,
    published_at TEXT NOT NULL,
    source TEXT,
    image_url TEXT,
    genre TEXT,
    symbol TEXT,
    is_bookmarked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create performance indexes for news
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_symbol ON news (symbol);
CREATE INDEX IF NOT EXISTS idx_news_is_bookmarked ON news (is_bookmarked);

-- 2. Create the 'watchlist' table
CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    attention_level TEXT CHECK (attention_level IN ('none', 'low', 'medium', 'high')) DEFAULT 'none',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create performance index for watchlist
CREATE INDEX IF NOT EXISTS idx_watchlist_symbol ON watchlist (symbol);

-- 3. Seed initial watchlist data
INSERT INTO watchlist (symbol, company_name, attention_level) VALUES
('AAPL', 'Apple Inc.', 'low'),
('GOOG', 'Alphabet Inc.', 'medium'),
('AMZN', 'Amazon.com, Inc.', 'none')
ON CONFLICT (symbol) DO NOTHING;

-- 4. Enable Row Level Security (RLS) & Enable anonymous operations
-- (Ensures browser clients using the anon key can read/write data for development)

ALTER TABLE news ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on news" ON news;
DROP POLICY IF EXISTS "Allow public insert access on news" ON news;
DROP POLICY IF EXISTS "Allow public update access on news" ON news;
DROP POLICY IF EXISTS "Allow public delete access on news" ON news;

CREATE POLICY "Allow public read access on news" ON news FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert access on news" ON news FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update access on news" ON news FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete access on news" ON news FOR DELETE TO public USING (true);

ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on watchlist" ON watchlist;
DROP POLICY IF EXISTS "Allow public insert access on watchlist" ON watchlist;
DROP POLICY IF EXISTS "Allow public update access on watchlist" ON watchlist;
DROP POLICY IF EXISTS "Allow public delete access on watchlist" ON watchlist;

CREATE POLICY "Allow public read access on watchlist" ON watchlist FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert access on watchlist" ON watchlist FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update access on watchlist" ON watchlist FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete access on watchlist" ON watchlist FOR DELETE TO public USING (true);
